# Расписание выполнения задачи
Schedule:
  timerJob: 10 # Частота запуска задачи в минутах
  dailyJob: # Время запуска задачи в формате HH:MM
    - 00:00:00
    - 06:45:00
    - 12:01:23
    - 19:59:03
    - 21:13:13
    - 22:47:03
# Настройки подключения к Zabbix
Zabbix:
  host: 192.168.9.45
  port: 80
  user: 803.p.vishnitsky@avz-center.ru
  timeout: 30
# Настройки подключения к NetBox
NetBox:
  host: localhost
  port: 4455
  user: someuser
InformationServerApi:
  host: localhost
  port: 8080
# Настройки подключения к БД для записи логов
WriteLogDataBase:
  host: datahook.cloud.gcm
  port: 9202
  user: log_writer.dev
  namedb:
  storage_name_db: enricher_zabbix_information
