# Расписание выполнения задачи
Schedule:
  timerJob: 10 # Частота запуска задачи в минутах
  dailyJob: # Время запуска задачи в формате HH:MM
    - 00:00:00
    - 06:00:00
    - 12:00:00
    - 15:59:00
    - 21:00:00
# Настройки подключения к Zabbix
Zabbix:
  use_tls: true # Использовать TLS для подключения к Zabbix
  host: 192.168.9.45
  port: 443
  user: 803.p.vishnitsky@avz-center.ru
  timeout: 30
# Настройки подключения к NetBox
NetBox:
  host: netbox.cloud.gcm
  port: 8005
InformationServerApi:
  host: localhost
  port: 8080
# Настройки подключения к БД для записи логов
WriteLogDataBase:
  host: database.cloud.example.prod
  port: 9200
  user: log_writer.prod
  namedb:
  storage_name_db: enricher_zabbix_information
