Zabbix:
  host: 192.168.9.45
  port: 80
  user: 803.p.vishnitsky@avz-center.ru
NetBox:
  host: localhost
  port: 4455
  user: someuser
WriteLogDataBase:
  host: database.cloud.example
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: application_template_db
