Zabbix:
  host: 192.168.9.45
  port: 80
  user: 803.p.vishnitsky@avz-center.ru
NetBox:
  host: localhost
  port: 4455
  user: someuser
WriteLogDataBase:
  host: datahook.cloud.gcm
  port: 9202
  user: log_writer.dev
  namedb:
  storage_name_db: enricher_zabbix_information
