# Расписание выполнения задачи
Schedule:
  timerJob: 10 # Частота запуска задачи в минутах
  dailyJob: # Время запуска задачи в формате HH:MM
    - 00:00:00
    - 06:00:00
    - 18:00:00
# Настройки подключения к Zabbix
Zabbix:
  use_tls: true # Использовать TLS для подключения к Zabbix
  host: 192.168.9.45
  port: 443
  user: 803.a.belyakov@avz-center.ru
  timeout: 30
# Настройки подключения к NetBox
NetBox:
  host: netbox.cloud.gcm
  port: 8005
InformationServerApi:
  host:
  port: 8989
# Настройки подключения к БД для записи логов
WriteLogDataBase:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: enricher_zabbix_information
