# Расписание выполнения задачи.
Schedule:
  timerJob: 1 # Частота запуска задачи в минутах
  dailyJob: # Время запуска задачи в формате HH:MM
    - 00:00:00
    - 06:00:00
    - 12:01:23
    - 16:05:03
    - 17:59:03
# Настройки подключения к Zabbix
Zabbix:
  use_tls: false # Использовать TLS для подключения к Zabbix
  host: localhost
  port: 8282
  user: api_user_1
  timeout: 30
# Настройки подключения к NetBox
NetBox:
  host: netbox.cloud.gcm
  port: 8005
InformationServerApi:
  host:
  port: 8989
# Настройки подключения к БД для записи логов
WriteLogDataBase:
  host: database.cloud.example
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: application_template_db
