# Расписание выполнения задачи.
Schedule:
  timerJob: 1 # Частота запуска задачи в минутах
  dailyJob: # Время запуска задачи в формате HH:MM
    - 00:00:00
    - 06:45:00
    - 12:01:23
    - 19:59:03
    - 21:13:13
    - 22:47:03
# Настройки подключения к Zabbix
Zabbix:
  host: 192.168.9.45
  port: 443
  user: 803.p.vishnitsky@avz-center.ru
  timeout: 30
# Настройки подключения к NetBox
NetBox:
  host: localhost
  port: 4455
InformationServerApi:
  host: localhost
  port: 8989
# Настройки подключения к БД для записи логов
WriteLogDataBase:
  host: database.cloud.example
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: application_template_db
