# Рассписание выполнения задачи
Schedule:
  timerJob: 10 # Частота запуска задачи в минутах
  dailyJob: # Время запуска задачи в формате HH:MM
    - 00:00:00
    - 06:00:00
    - 12:00:00
# Настройки подключения к Zabbix
Zabbix:
  host: 192.168.9.45
  port: 80
  user: 803.p.vishnitsky@avz-center.ru
# Настройки подключения к NetBox
NetBox:
  host: localhost
  port: 4455
  user: someuser
# Настройки подключения к БД для записи логов
WriteLogDataBase:
  host: database.cloud.example.prod
  port: 9200
  user: log_writer.prod
  namedb:
  storage_name_db: enricher_zabbix_information
